blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:id>/', views.post_detail, name='post_detail'),
    path('ticket/', views.ticket, name='ticket'),
    path('post_detail/<int:post_id>/comment',
         views.commnet_post, name='comment_post'),
    path('create-post/', views.createpost, name='create-post'),
    path('search-post/', views.search_post, name='search-post'),
    path('profile/', views.profile, name='profile'),
    path('delete-post/<int:post_id>', views.delete_post, name='delete-post')
]

topic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django_jalali.db import models as jmodels
from django.urls import reverse
from django_resized import ResizedImageField
from django.utils.text import slugify 


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        PUBLISHED = 'PB', 'انتشار'
        DRAFT = 'DF', 'پیش نویس'
        REJECTED = 'RE', 'رد شده'

    title = models.CharField(max_length=250, verbose_name='عنوان')
    description = models.TextField(verbose_name='جزئیات')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='کاربر', related_name="user")
    created = jmodels.jDateTimeField(
        auto_now_add=True, verbose_name='تاریخ ایجاد')
    updated = jmodels.jDateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')
    publish = jmodels.jDateTimeField(
        default=timezone.now, verbose_name='تاریخ انتشار')
    slug = models.SlugField(max_length=250, verbose_name='اسلاگ')
    status = models.CharField(
        max_length=100, choices=Status, default=Status.DRAFT, verbose_name='وضعیت')
    reading_time = models.PositiveIntegerField(verbose_name='زمان مطالعه')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
        ]
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)


class Ticket(models.Model):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش مشکل')
    )
    name = models.CharField(max_length=250)
    message = models.TextField()
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    subject = models.CharField(max_length=250, choices=SUBJECT_CHOICES)

    class Meta:
        ordering = ['-name']
        indexes = [
            models.Index(fields=['-name']),
        ]
        verbose_name = 'تیکت'
        verbose_name_plural = 'تیکت ها'

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments', verbose_name='پست')
    name = models.CharField(max_length=250, verbose_name='نام شما')
    message = models.TextField(verbose_name='متن کامنت')
    created = jmodels.jDateTimeField(
        auto_now_add=True, verbose_name='تاریخ ایجاد')
    active = models.BooleanField(default=False, verbose_name='وضعیت کامنت')

    class Meta:
        ordering = ('-name', )
        indexes = [
            models.Index(fields=['-name']),
        ]
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'

    def __str__(self):
        return self.name


class Image(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='image', verbose_name='پست')
    title = models.CharField(
        max_length=300, verbose_name='عنوان تصویر', null=True, blank=True)
    description = models.TextField(
        verbose_name='جزئیات تصویر', null=True, blank=True)
    image = ResizedImageField(verbose_name="تصویر", upload_to='post_image', size=[
                              500, 500], quality=75, crop=['middle', 'center'])

    class Meta:
        ordering = ('-title', )
        indexes = [
            models.Index(fields=['-title'])
        ]
        verbose_name = "تصویر"
        verbose_name_plural = "تصاویر"
        
        
    def __str__(self):
        return self.title if self.title else f'{self.image.name}'

blog/forms.py
from email.policy import default
from django import forms
from .models import *


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش مشکل')
    )
    name = forms.CharField(max_length=100, required=True, label='نام')
    message = forms.CharField(widget=forms.Textarea,
                              required=True, label='متن')
    email = forms.EmailField(label='ایمیل', required=False)
    phone = forms.CharField(max_length=11, required=True, label='شماره موبایل')
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label='موضوع')

    def clean_name(self):
        entry_name = self.cleaned_data['name']
        if entry_name:
            if not entry_name.replace(' ', '').isalpha() or len(entry_name) < 3:
                raise forms.ValidationError('نام خود را صحیح وارد کنید')
            else:
                c = 0
                name = ''
                space = False
                for i in entry_name:
                    if i.isalpha():
                        name += i
                        c += 1
                        if c >= 3:
                            space = True
                    if i.isspace() and space:
                        name += i
                        space = False
                        c = 0
                return name

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric() or len(phone) != 11:
                raise forms.ValidationError('شماره موبایل صحیح نیس!')
            else:
                return phone

    def clean_message(self):
        message = self.cleaned_data['message']
        if message:
            if len(message.replace(' ', '')) < 10:
                raise forms.ValidationError('پیام شما کوتاه است')
            else:
                return message


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'message']


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", required=False)
    image2 = forms.ImageField(label="تصویر دوم", required=False)
    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time']
        
class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.http import HttpResponse
from django.core.paginator import Paginator
from .forms import *
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.db.models.functions import Greatest


def home_page(request):
    return render(request, 'pages/home_page.html')


def post_list(request):
    posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_num = request.GET.get('page', 1)
    page = paginator.get_page(page_num)
    posts = page
    context = {
        'posts': posts
    }
    return render(request, 'pages/post_list.html', context)


def post_detail(request, id):
    post = get_object_or_404(Post.published.all(), pk=id)
    form = CommentForm()
    comment = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, 'pages/post_detail.html', context)


def ticket(request):
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                name=cd['name'],
                message=cd['message'],
                phone=cd['phone'],
                email=cd['email'],
                subject=cd['subject'],
            )
            return redirect('blog:ticket')
    else:
        form = TicketForm()
    context = {
        'form': form
    }
    return render(request, 'forms/ticket.html', context)


@require_POST
def commnet_post(request, post_id):
    post = get_object_or_404(Post.published.all(), id=post_id)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    else:
        form = CommentForm()
    context = {
        'form': form,
        'post': post,
        'comment': comment,
    }
    return render(request, 'forms/comment_post.html', context)


def createpost(request):
    post = None
    created = False
    form = PostForm(request.POST, request.FILES)
    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        Image.objects.create(image=form.cleaned_data['image1'], post=post)
        Image.objects.create(image=form.cleaned_data['image2'], post=post)
        created = True
    else:
        form = PostForm()

    context = {
        'form': form,
        'post': post,
        'created': created
    }
    return render(request, 'forms/postform.html', context)


def search_post(request):
    # print(request.GET.get('query'))
    query = None
    results = []
    found = False
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results1 = Post.published.annotate(similarity=TrigramSimilarity('title', query)).filter(similarity__gt=0.1).order_by('-similarity')
            results2 = Post.published.annotate(similarity=TrigramSimilarity('description', query)).filter(similarity__gt=0.05).order_by('-similarity')
            results3 = Post.published.annotate(similarity=TrigramSimilarity('image__title', query)).filter(similarity__gt=0.1).order_by('-similarity')
            results4 = Post.published.annotate(similarity=TrigramSimilarity('image__description', query)).filter(similarity__gt=0.05).order_by('-similarity')
            
            results = (results1 | results2 | results3 | results4)

            results = sorted(results, key=lambda x: x.similarity, reverse=True)
            found = bool(results)
            paginator = Paginator(results, 3)
            num_page = request.GET.get('page', 1)
            page = paginator.get_page(num_page)
            results = page

    context = {
        'query': query,
        'results': results,
        'found': found,
    }

    return render(request, 'pages/searchpost.html', context)


def profile(request):
    user = request.user
    if not user.is_anonymous:
        posts = Post.objects.filter(user=user)
        context = {
            'posts': posts,
            'user': user
        }
        return render(request, 'pages/profile.html', context)
    else:
        return HttpResponse("login first!")
    
    
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    
    context = None
    return render(request, 'pages/confirm_delete.html')

blog/templates/pages/confirm_delete.html
{% extends 'parent/base.html' %}

{% block title %} تایید حذف پست {% endblock %}

{% block content %}
    <center><h2>آیا از حذف پست مطمئن هستید؟!</h2></center>
    <br>
    <br>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="تایید می کنم">
    </form>
    <hr>
    <h3><a href="{% url 'blog:profile' %}">صفحه پروفایل</a></h3>
    {% include 'partials/bthp.html' %}
{% endblock content %}

blog/templates/pages/home_page.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}
{% block title %}صفحه خانه{% endblock %}
{% block content %}
{% mpp as pop_post %}
{% lpd as lpp %}
<center><h1>خوش آمدید</h1></center>
<h3>کل پست های منتشر شده: {% total_posts %}</h3>
<h3>تعداد کل کامنت ها: {% total_comments %}</h3>
<h3>آخرین پست منتشر شده: {{ lpp | jformat:'%d / %m / %Y' }}</h3>
<h3>آخرین پست ها: {% latest_posts 2 %}</h3>
<h3>محبوب ترین پست ها</h3>

{% for pp in pop_post %}
<a href="{{ pp.get_absolute_url }}">{{pp.title}}</a>
{% endfor %}

<br>
<p><a href="admin/">ورود به پنل ادمین</a></p>
<p><a href="{% url 'blog:profile' %}">صفحه پروفایل</a></p>
<p><a href="{% url 'blog:post_list' %}">لیست پست ها</a></p>
<p><a href="{% url 'blog:create-post' %}">ایجاد پست</a></p>
<p><a href="{% url 'blog:ticket' %}">ثبت تیکت</a></p>

{% endblock %}

blog/templates/pages/post_detail.html
{% extends 'parent/base.html' %}
{% load jformat %}

{% block title %}
پست {{ post.title }}
{% endblock title %}

{% block content %}
<p>عنوان :{{ post.title }}</p>
<p>جزئیات :{{ post.description | linebreaks}}</p>
<p>تاریخ انتشار :{{ post.publish | jformat:'%d / %m / %Y' }}</p>
<p>ساعت :{{ post.publish | jformat:'%m:%I' }}</p>
<p>نویسنده :{{ post.user }}</p>


{% for img in post.image.all %}
    <img src="{{ img.image.url }}" alt=" img.image.title ">
    <p>{{img.title}}</p>
    <p>{{ img.description }}</p>
    <br>
    
{% endfor %}
    
<br>
<hr>
{% if comment %}
<p>{{ commnet.count }} کامنت ها</p>
<br>
{% for cm in comment %}
<p>نام: {{ cm.name }}</p>
<p>متن کامنت: {{ cm.message }}</p>
<hr>
{% endfor %}
{% else %}
<p>کامنتی وجود ندارد</p>
{% endif %}
<br>
<hr>
<p>ثبت کامنت</p>
<form method="post" action="{% url 'blog:comment_post' post.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="ثبت کامنت">
</form>
<br>
<a href="{% url 'blog:post_list' %}"><p>بازگشت به پست ها</p></a>
{% include 'partials/bthp.html' %}
{% endblock content %}

blog/templates/pages/post_list.html
{% extends 'parent/base.html' %}
{% block title %}لیست پست ها{% endblock %}
{% block content %}
<h1>لیست پست ها</h1>
<br>
{% for post in posts %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
<p>{{ post.description | linebreaks }}</p>
<img src="{{ post.image.first.image.url }}" >
<hr>
{% endfor %}
    {% include 'partials/pagination.html' with page=posts %}
    {% include 'partials/bthp.html' %}
{% endblock content %}

blog/templates/pages/profile.html
{% extends 'parent/base.html' %}
{% load jformat %}


{% block title %}صفحه پروفایل{% endblock title %}


{% block content %}
    <center><h1>پروفایل شما</h1></center>
    <br>
    <br>
    <h3>نام: {{ user.first_name }}</h3>
    <h3>نام خانودادگی: {{ user.last_name }}</h3>
    <h3>نام کاربری: {{ user.username }}</h3>

    <br>
    <br>
    <hr>
    <center><h1>پست های شما</h1></center>
    <br>
    
    {% for post in posts %}
        <h3>عنوان: {{ post.title }}</h3>
        <h4>جزئیات: {{ post.description }}</h4>
        <h4>تاریخ ایجاد: {{ post.created | jformat:'%d / %m / %Y' }}</h4>
        <h4>تاریخ آپدیت: {{ post.updated | jformat:'%d / %m / %Y' }}</h4>
        <h4>تاریخ انتشار: {{ post.publish | jformat:'%d / %m / %Y' }}</h4>
        <h4>زمان مطالعه: {{ post.reading_time }}</h4>
        {% if post.status == 'PB' %}
            <h4>وضعیت: منتشر شده</h4>
        {% elif post.status == 'DF' %}
            <h4>وضعیت: منتشر نشده</h4>
        {% else %}
            <h4>وضعیت: رد شده</h4>
        {% endif %}
        <h3><a href="{% url 'blog:delete-post' post.id %}">حذف پست</a></h3>
        <hr>
    {% endfor %}

    {% include 'partials/bthp.html' %}


{% endblock content %}

blog/templates/pages/searchpost.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% block title %}
جست و جوی پست
{% endblock title %}

{% block content %}

{% if found %}
<center><h1>نتایج جست و جو</h1></center>
<br>
<br>

{% for post in results %}
<hr>
<a href="{{post.get_absolute_url}}">{{ post.title }}</a>
<br>
<p>{{ post.description | linebreaks }}</p>

{% if post.image.first %}
    <img src="{{ post.image.first.image.url }}" alt="post.image.title">
{% endif %}
<p>{{ post.publish | jformat:'%d / %m / %Y'}}</p>
{% endfor %}

{% else %}

<center><h1>چیزی یافت نشد!</h1></center>
<br>
<br>
{% endif %}
{% include 'partials/pagination.html' with page=results query=query %}
{% include 'partials/bthp.html' %}
{% endblock content %}